version: '3'
services:
  backend:
    build: backend
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment: 
      SECRET_KEY: 123 
      DEBUG: 'True' 
      SOCIAL_AUTH_TWITTER_KEY: 'your-secret-key'
      SOCIAL_AUTH_TWITTER_SECRET: 'your-secret-key'
      DATABASE_URL: postgres://pyconsite@postgres/pycon 

    command: "python manage.py runserver 0.0.0.0:8000"    
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:9.6.8-alpine@sha256:49f5c42990833857f4caa6d06437b3ce6391e830b05e07c11c6c7737be535649
    environment:
      POSTGRES_USER: pyconsite
      POSTGRES_DB: pycon

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
   